name: Documentation Check
on:
  pull_request:
  push:
    branches:
      - main

jobs:
  sphinx:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: XanaduAI/sphinx-action@master
      with:
        docs-folder: "docs/"
        pre-build-command: "apt install -y git graphviz && pip3 install . && pip3 install -r docs/requirements.txt"
        build-command: "sphinx-build -b html . _build -W --keep-going"